services:
  postgres_db:
    image: postgres:17.0-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-softagon_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-softagon_password}
      POSTGRES_DB: ${POSTGRES_DB:-softagon_db}
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - 5436:5432
volumes:
  postgresql_data: